name: "Variables Allocation"
description: "Replace placeholders on an .env template file to a functional env file ready to use on production"
inputs:
  ENV_FILE_IN:
    description: "Path to the .env file template"
    required: true
  ENV_FILE_OUT:
    description: "Path to the .env file processed"
    required: true
  REPO_VARS:
    description: "Environment variables allocated on current repo"
    required: true
  REPO_SECRETS:
    description: "Environment secrets allocated on current repo"
    required: true
outputs:
  CLOUDFRONT_DIST_ID:
    description: "Resolved CloudFront distribution ID from vars or secrets"
    value: ${{ steps.entrypoint.outputs.CLOUDFRONT_DIST_ID }}
runs:
  using: "composite"
  steps:
    - id: entrypoint
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/entrypoint.sh
        ${{ github.action_path }}/entrypoint.sh
      env:
        ENV_FILE_IN: ${{ inputs.ENV_FILE_IN }}
        ENV_FILE_OUT: ${{ inputs.ENV_FILE_OUT }}
        REPO_VARS: ${{ inputs.REPO_VARS}}
        REPO_SECRETS: ${{ inputs.REPO_SECRETS}}
